"""Visualize TagR scores produced by asm3_risk_tagging.py as a heatmap."""
from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

EXPERIMENTS: Sequence[Tuple[str, str]] = (
    ("Results_ExpLength_4h", "4h"),
    ("Results_ExpLength_5h", "5h"),
    ("Results_ExpLength_6h", "6h"),
    ("Results_ExpLength_7h", "7h"),
)

SOURCES: Sequence[Tuple[str, str, str]] = (
    ("reactor1", "R1", "reactor1_data_iteration_{iter_id}.csv"),
    ("reactor2", "R2", "reactor2_data_iteration_{iter_id}.csv"),
    ("reactor3", "R3", "reactor3_data_iteration_{iter_id}.csv"),
    ("reactor4", "R4", "reactor4_data_iteration_{iter_id}.csv"),
    ("reactor5", "R5", "reactor5_data_iteration_{iter_id}.csv"),
    ("settler", "S", "settler_data_DR_iteration_{iter_id}.csv"),
)

CMAP = mcolors.ListedColormap(["black", "green", "yellow", "orange", "red"])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-dir",
        default=Path("/Users/aya/github/WWDR/8AM_ASM3_DB/Tagged_Datasets"),
        type=Path,
        help="Root directory that holds Results_ExpLength_* folders generated by asm3_risk_tagging.py.",
    )
    parser.add_argument(
        "--iterations",
        nargs="*",
        help="Optional list of iteration folder names to plot (e.g. iter245 iter259). Defaults to the common intersection across experiments.",
    )
    parser.add_argument(
        "--save-path",
        type=Path,
        help="Optional path to save the figure instead of displaying it interactively.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        help="Logging verbosity.",
    )
    return parser.parse_args()


def read_tagR(csv_path: Path) -> np.ndarray:
    df = pd.read_csv(csv_path)
    for key in ("tagR", "TagR"):
        if key in df.columns:
            return df[key].to_numpy()
    raise KeyError(f"TagR column not found in {csv_path}")


def available_iterations(base_dir: Path) -> Dict[str, List[str]]:
    mapping: Dict[str, List[str]] = {}
    for exp_dir, _ in EXPERIMENTS:
        root = base_dir / exp_dir / "ASM3_OutputDB"
        if not root.exists():
            raise FileNotFoundError(f"Missing output directory: {root}")
        iters = sorted(p.name for p in root.iterdir() if p.is_dir())
        if not iters:
            raise FileNotFoundError(f"No iteration folders under {root}")
        mapping[exp_dir] = iters
    return mapping


def resolve_iterations(requested: Iterable[str] | None, mapping: Dict[str, List[str]]) -> List[str]:
    if requested:
        requested = list(dict.fromkeys(requested))
        missing = [name for name in requested if any(name not in iters for iters in mapping.values())]
        if missing:
            raise FileNotFoundError(f"Requested iterations are unavailable in every experiment: {missing}")
        return list(requested)

    common = set(mapping[next(iter(mapping))])
    for iters in mapping.values():
        common &= set(iters)
    if not common:
        raise ValueError("No common iteration folders found across experiment lengths")
    return sorted(common)


def load_all_tagR(
    base_dir: Path,
    iterations: Sequence[str],
) -> Tuple[Dict[Tuple[str, str, str], np.ndarray], int]:
    cache: Dict[Tuple[str, str, str], np.ndarray] = {}
    min_len = None

    for exp_dir, _ in EXPERIMENTS:
        exp_root = base_dir / exp_dir / "ASM3_OutputDB"
        for iteration in iterations:
            iter_id = iteration.replace("iter", "")
            for source_key, _, template in SOURCES:
                csv_path = exp_root / iteration / template.format(iter_id=iter_id)
                if not csv_path.exists():
                    raise FileNotFoundError(f"Missing CSV: {csv_path}")
                series = read_tagR(csv_path)
                cache[(exp_dir, source_key, iteration)] = series
                current_len = len(series)
                if min_len is None or current_len < min_len:
                    min_len = current_len
    assert min_len is not None
    return cache, min_len


def build_matrix(
    cache: Dict[Tuple[str, str, str], np.ndarray],
    iterations: Sequence[str],
    block_len: int,
) -> Tuple[np.ndarray, List[str]]:
    rows: List[np.ndarray] = []
    labels: List[str] = []

    for source_key, source_label, _ in SOURCES:
        for exp_dir, exp_label in EXPERIMENTS:
            labels.append(f"{source_label} {exp_label}")
            segments = [cache[(exp_dir, source_key, iteration)][:block_len] for iteration in iterations]
            rows.append(np.concatenate(segments))

    matrix = np.vstack(rows)
    return matrix, labels


def plot_heatmap(matrix: np.ndarray, labels: Sequence[str], iterations: Sequence[str], save_path: Path | None) -> None:
    block_len = matrix.shape[1] // len(iterations)
    fig, ax = plt.subplots(figsize=(14, 8))
    im = ax.imshow(matrix, aspect="auto", cmap=CMAP, interpolation="nearest", vmin=0, vmax=4)

    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels)

    tick_positions = [(idx + 0.5) * block_len for idx in range(len(iterations))]
    ax.set_xticks(tick_positions)
    ax.set_xticklabels(iterations, rotation=45, ha="right")
    ax.set_xlabel("Iterations (TagR samples concatenated)")
    ax.set_title("ASM3 TagR Heatmap by Reactor and Experiment Length")

    cbar = plt.colorbar(im, ticks=[0, 1, 2, 3, 4])
    cbar.set_label("TagR")

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=300)
        logging.info("Figure saved to %s", save_path)
    else:
        plt.show()


def main() -> None:
    args = parse_args()
    logging.basicConfig(level=getattr(logging, args.log_level.upper()), format="%(levelname)s: %(message)s")

    iteration_map = available_iterations(args.base_dir)
    iterations = resolve_iterations(args.iterations, iteration_map)
    logging.info("Using iterations: %s", ", ".join(iterations))

    cache, block_len = load_all_tagR(args.base_dir, iterations)
    logging.debug("Minimum TagR segment length per iteration: %d", block_len)

    matrix, labels = build_matrix(cache, iterations, block_len)
    plot_heatmap(matrix, labels, iterations, args.save_path)


if __name__ == "__main__":
    main()
