% This is an inititialization file for the BSM2 influent generation model
% Xavier Flores-Alsina
% IEA, LTH, Sweden
% June 2010

% Load influent flow rate data files, households (HH)
load day_HS
load week_HS
load year_HS

% Load influent flow rate data files, Industry (IndS)
load week_IndS
load year_IndS

% Load influent pollution load, households (HH)
load CODsol_day_HS
load CODpart_day_HS
load SNH_day_HS
load PO4_day_HS

load week_polHS

% Load influent pollution load, Industry (IndS)
load CODsol_week_IndS
load CODpart_week_IndS
load SNH_week_IndS
load PO4_week_IndS

%% 1.Households model block (flow rate)
% 1.1 Model parameters
QperPE = 150;                              % Wastewater flow rate per person equivalent for municipal wastewater
PE     = 80;                               % Number of HH person equivalent connected to the WWTP
QHHsatmin = 0.001;                         % In l/d; if equal to zero, problems might occur when generating concentrations based on fluxes (division by zero)
QHHsatmax = QperPE*50;                     % In l/d

% 1.2. Noise parameters
Q_HH_ns=3857;                              % Noise seed
Q_HH_nv=4000;                              % Noise variance (can be switched on or off with HHnoiseswitch)
Q_HH_st=1/24;                              % Noise sampling time

% 1.3 switch functions
HHpopswitch     = 100;                     % Switch the HH contribution on (100%) or off (0%)
HHnoiseswitch = 1;                         % Switch the noise term in HH flow rate  on (1) or off (0)


%% 2.Industry model block (flow rate)
%2.1 model parameters
QInd_weekday = 2500;                       % Average wastewater production industry, for normal week-days
QIndsatmin=0.001;                          % In m3/d; if equal to zero, problems might occur when generating concentrations based on fluxes (division by zero)
QIndsatmax=QInd_weekday*10;                % In m3/d

% 2.2 Noise parameters
Q_Ind_ns=2000;                             % Noise seed
Q_Ind_nv=15000;                            % Noise variance (can be switched on or off with Indnoiseswitch)
Q_Ind_st=1/24;                             % Noise sampling time

% 2.3 switch functions
Indpopswitch=100;                          % Switch the Industrial contribution on (100%) or off (0%)
Indnoiseswitch = 1;                        % Switch noise term in the 'Industry' model block on (1) or off (0)

%% 3. Seasonal correction factor (flow rate)
% 3.1. Model parameters
InfAmp = 1200;                              % Sine wave amplitude (m3/d)
InfBias = 7100;                             % Sine wave bias (m3/d) (= average infiltration flow rate)
InfFreq = 2*pi/364;                         % Sine wave frequency (rad/d)
InfPhase = -pi*15/24;                       % Sine wave phase shift
Infcst = 7100;                              % Constant flow rate (m3/d), used when the sine wave is not selected (manual selection possible in 'Groundwater' model block

QSCIsatmin=0.0;                             % In m3/d, if equal to zero, problems might occur when generating concentrations based on fluxes (division by zero)
QSCIsatmax=2*(InfBias+InfAmp);              % In m3/d

%3.2. Noise parameters 
Q_SCI_ns=1000;                              % Noise seed
Q_SCI_nv=0.1*InfBias;                       % Noise variance (can be switched on or off with SCInoiseswitch)
Q_SCI_st=1;                                 % Noise sampling time

% 3.3. switch functions
SCIpopswitch=100;                           % Switch the infiltration contribution on (100%) or off (0%)
SCInoiseswitch=0;                           % Switch noise term in the 'Seasonal correction infiltration' model block on (1) or off (0) (Normally off!!!)

%% 4. rain generation model block (flow-rate)
% 4.1. model parameters
LLrain=3.5;                                 % Limit for rain (this value is subtracted from the values generated by the random number generator)
Qpermm=1500;                                % Flow rate due to rain (m3/mm)
aHpercent=75;                               % Assumed percentage of the extra flow due to rain that originates from impervious areas, where water 
                                            % is directly collected in the sewer system. In the
                                            % model, the conversion aH = aHpercent/100 is made.
rainmax = 1000;                             % max signal after the transfer function
rainmin = 0;                                % min signal after the transfer function

% 4.2. Noise parameters
rain_ns=3000;                               % Noise seed
rain_nm=1;                                  % Noise mean
rain_nv=400;                                % Noise variance
rain_st=1/24;                               % Noise sampling time

%4.3 switch functions
rainpopswitch=100;                          % Switch the rain contribution on (100%) or off (0%)

%% 5 soil model accumulation block (flow rate)
% 5.1. Initial state
XINITSOIL=2.2;                              % Initial h1 value. 

% 5.2. Parameters S-function
subareas = 4;                               % Subareas the catchment is divided
HINV=2;                                     % Invert level in tank, i.e. water level corresponding to bottom of sewer pipes
HMAX=HINV+0.8;                              % Maximum water level in tank
A=36000;                                    % Surface area
K=1.0;                                      % Parameter, permeability of soil for water penetration
Kinf=2500.0*subareas;                       % Infiltration gain, can be an indication of the quality of the sewer system pipes
Kdown=1000.0;                               % Gain to adjust for flow rate to downstream aquifer

PARS_SOIL=[HMAX HINV A K Kinf Kdown];       % Parameter vector, an input to the unisoilmodel.c S-function

%% 6.Households model block (pollutantans)
%6.1. Model parameters
CODsol_gperPEperd=19.31;                    % Soluble COD load in g COD/d per PE
CODpart_gperPEperd=115.08;                  % Particulate COD load in g COD/d per PE
SNH_gperPEperd=6.89*0.85;                   % Ammonium load in g N/d per PE %%%% !!!!!!!!!!!!!!reivse this value!!!!!!!!!!!!!
PO4_gperPEperd=(6.89*0.85)/4;               % PO4 load in g P/d per PE %%%% !!!!!!!!!!!!!!reivse this value!!!!!!!!!!!!!

CODsol_HH_min=0.1;                          % kg COD/d
CODsol_HH_max=20*CODsol_gperPEperd*PE;      % kg COD/d
CODpart_HH_min=0.1;                         % kg COD/d
CODpart_HH_max=20*CODpart_gperPEperd*PE;    % kg COD/d
SNH_HH_min=0.1;                             % kg N/d
SNH_HH_max=20*SNH_gperPEperd*PE;            % kg N/d
PO4_HH_min=0.1;                             % kg P/d
PO4_HH_max=20*PO4_gperPEperd*PE;            % kg P/d


% 6.2. Noise parameters
factor1 = 2.0;                              % Proportionality factor random noise generators

CODsol_HH_ns=25000;                         % Noise seed, CODsol
CODsol_HH_nv=factor1*2*CODsol_gperPEperd*PE;% Noise variance (can be switched on or off with HHpolnoiseswitch), CODsol
CODsol_HH_st=1/24;                          % Noise sampling time, CODsol
CODpart_HH_ns=35000;                        % Noise seed, CODpart
CODpart_HH_nv=factor1*CODpart_gperPEperd*PE;% Noise variance (can be switched on or off with HHpolnoiseswitch), CODpart
CODpart_HH_st=1/24;                         % Noise sampling time, CODpart
SNH_HH_ns=45000;                            % Noise seed, SNH
SNH_HH_nv=factor1*2*SNH_gperPEperd*PE;      % Noise variance (can be switched on or off with HHpolnoiseswitch), SNH
SNH_HH_st=1/24;                             % Noise sampling time, SNH
PO4_HH_ns=55000;                            % Noise seed, SPO4
PO4_HH_nv=factor1*2*PO4_gperPEperd*PE;      % Noise variance (can be switched on or off with HHpolnoiseswitch), SPO4
PO4_HH_st=1/24;                             % Noise sampling time, SPO4


%6.3 Switch functions
HHpolnoiseswitch = 1;                       % Switch noise term in the 'HH pollution loads' model block on (1) or off (0)

%% 7. Industry model block (pollutants)
% 7.1. Model parameters
CODsol_Ind_kgperd=386.24;                   % Soluble COD load in kg COD/d
CODpart_Ind_kgperd=2301.80;                 % Particulate COD load in kg COD/d !!!!!!!!!!!!!!revise this value!!!!!!!!!!!!!
SNH_Ind_kgperd=61.25*0.85;                  % Ammonium load in kg N/d !!!!!!!!!!!!!!revise this value!!!!!!!!!!!!!
PO4_Ind_kgperd=(61.25*0.85)/4;              % PO4 load in kg N/d !!!!!!!!!!!!!!revise this value!!!!!!!!!!!!!

CODsol_Ind_max=20*CODsol_Ind_kgperd;        % kg COD/d
CODsol_Ind_min=0.1;                         % kg COD/d
CODpart_Ind_max=20*CODpart_Ind_kgperd;      % kg COD/d
CODpart_Ind_min=0.1;                        % kg COD/d
SNH_Ind_max=20*SNH_Ind_kgperd;              % kg N/d
SNH_Ind_min=0.1;                            % kg N/d
PO4_Ind_max=20*PO4_Ind_kgperd;              % kg P/d
PO4_Ind_min=0.1;                            % kg P/d

% 7.2 Noise parameters
factor2=2.0;

CODsol_Ind_ns=11000;                        % Noise seed
CODsol_Ind_nv=factor2*CODsol_Ind_kgperd;    % Noise variance (can be switched on or off with Indpolnoiseswitch), CODsol
CODsol_Ind_st=1/24;                         % Noise sampling time, CODsol
CODpart_Ind_ns=21000;                       % Noise seed
CODpart_Ind_nv=factor2*CODpart_Ind_kgperd;  % Noise variance (can be switched on or off with Indpolnoiseswitch), CODpart
CODpart_Ind_st=1/24;                        % Noise sampling time, CODpart
SNH_Ind_ns=31000;                           % Noise seed
SNH_Ind_nv=factor2*SNH_Ind_kgperd;          % Noise variance (can be switched on or off with Indpolnoiseswitch), SNH
SNH_Ind_st=1/24;                            % Noise sampling time, SNH
PO4_Ind_ns=41000;                           % Noise seed
PO4_Ind_nv=factor2*PO4_Ind_kgperd;          % Noise variance (can be switched on or off with Indpolnoiseswitch), PO4
PO4_Ind_st=1/24;                            % Noise sampling time, PO4

%7.3 Switch functions
Indpolnoiseswitch=1;                        % Switch noise term in the 'Industry_pollutants' model block on (1) or off (0)

%% 8. Influent fractionation model (ASM1)

% 8.1. Model parameters
%Initial ASM2d model parameters

So_in   =  0.00;
Sa_in   =  69.50 * 0.4;
Sf_in   =  69.50 * 0.6;
Si_in   =  30.00;
Snh_in  =  31.56;
Sn2_in  =  0.00;
Sno_in  =  0.00;
Spo4_in =  9.01;
Salk_in =  7.00;
Xi_in   =  51.20;
Xs_in   =  202.32;
Xbh_in  =  28.17;
Xpao_in =  0.00;
Xpp_in  =  0.00;
Xpha_in =  0.00;
Xba_in  =  0.00;
TSS_in  =  211.27;		
Xmeoh_in=  0.00;
XMep    =  0.00;

% ASM2d kinetics and stoichiometrics
f_SI     = 	0.00;    
Y_H      = 	0.625;   
Y_PAO    =	0.625;  
Y_PO4    =	0.40;    
Y_PHA    =	0.20;    
Y_A      =	0.24;    
f_XIH    =	0.10;    
f_XIP    =	0.10;    
f_XIA    =	0.10;    
iN_SI    =	0.01;    
iN_SF    =	0.03;    
iN_XI    =	0.02;    
iN_XS    =	0.04;    
iN_BM    =	0.07;   
iP_SI    =	0.00;    
iP_SF    =	0.01;    
iP_XI    =	0.01;    
iP_XS    =	0.01;    
iP_BM    =	0.02;    
iSS_XI   =	0.75;    
iSS_XS   =	0.75;    
iSS_XB   =	0.90;
iSS_XPP  =  3.23;
iSS_XPHA =  0.60;
iSS_XMe  =  1.00;
k_H      =  2.46;    
hL_NO3   =	0.60;    
hL_fe    =	0.40;    
KL_O2    =	0.20;    
KL_NO3   =	0.50;    
KL_X     =	0.10;    
Mu_H     =  4.23;    
q_fe     =  2.11;    
hH_NO3   =	0.80;    
b_H      =  0.28;    
KH_O2    =  0.20;    
K_F      =	4.00;    
K_fe     =  4.00;    
KH_A     =  4.00;    
KH_NO3   =	0.50;    
KH_NH4   =	0.05;    
KH_PO4   =	0.01;    
KH_ALK   =	0.10;    
q_PHA    =	2.46;    
q_PP     =	1.23;    
Mu_PAO   =	0.82;    
hP_NO3   =	0.60;    
b_PAO    =	0.14;    
b_PP     =	0.14;    
b_PHA    =	0.14;    
KP_O2    =	0.20;    
KP_NO3   =	0.50;    
KP_A     =	4.00;    
KP_NH4   =	0.05;   
KP_P     =	0.20;    
KP_PO4   =	0.01;    
KP_ALK   =	0.10;    
KP_PP    =	0.01;    
K_MAX    =	0.34;   
KI_PP    =	0.02;    
KP_PHA   =	0.01;    
Mu_A     =	0.61;    
b_A      =	0.09;    
KA_O2    =	0.50;    
KA_NH4   =	1.00;    
KA_ALK   =	0.50;    
KA_PO4   =	0.01;    
k_PRE    =	1.00;    
k_RED    =	0.60;    
KPr_ALK  =	0.50;    

ASM2d_PARS = [f_SI Y_H Y_PAO Y_PO4 Y_PHA Y_A f_XIH f_XIP f_XIA iN_SI iN_SF iN_XI iN_XS iN_BM iP_SI iP_SF iP_XI iP_XS iP_BM iSS_XI iSS_XS iSS_XB iSS_XPP iSS_XPHA iSS_XMe       k_H hL_NO3 hL_fe KL_O2 KL_NO3 KL_X Mu_H q_fe hH_NO3 b_H KH_O2 K_F K_fe KH_A KH_NO3 KH_NH4 KH_PO4 KH_ALK q_PHA q_PP Mu_PAO hP_NO3 b_PAO b_PP b_PHA KP_O2 KP_NO3 KP_A KP_NH4 KP_P KP_PO4 KP_ALK KP_PP K_MAX KI_PP KP_PHA Mu_A b_A KA_O2 KA_NH4 KA_ALK KA_PO4 k_PRE k_RED KPr_ALK];

% ASM2d fractions

Sa_fr   =  0.40;                            % SA as fraction of soluble COD
Sf_fr   =  0.60;                            % SF as fraction of soluble COD
Si_cst  =  30.00;                           % SI is not defined as a fraction of soluble COD, but as a constant concentration
                                            % It is assumed that SI is also present in the infiltration water. Only rain can dilute SI
SNH_fr  =  1.00;                            % Snh is the entire fraction of the entering NH4+ 
SNO_fr  =  1.00;
SPO4_fr =  1.00;                            % Spo4 is the entire fraction of the entering PO4-3 

XI_fr   =  0.182;                           % XI as fraction of particulate COD
XS_fr   =  0.718;                           % XS as fraction of particulate COD
XBH_fr  =  0.100;                           % XBH as fraction of particulate COD

ASM2d_FRACTIONS =[Sa_fr Sf_fr Si_cst SNH_fr SNO_fr SPO4_fr XI_fr XS_fr XBH_fr];             % Parameter vector (fractions), an input to the asm2d_fractionation.c S-function

%8.2 Noise parameters 

factor3 = 2;

% ASM2d noise parameters
SA_ns=03122;                                % Noise seed, SA
SA_nv=factor3*(Sa_in);                      % Noise variance (can be switched on or off with polnoiseswitch), SA
SA_st=1/24;                                 % Noise sampling time, SA
SF_ns=23122;                                % Noise seed, SF
SF_nv=factor3*(Sf_in);                      % Noise variance (can be switched on or off with polnoiseswitch), SF
SF_st=1/24;                                 % Noise sampling time, SF
SI_ns=13122;                                % Noise seed, SI
SI_nv=factor3*(Si_in);                      % Noise variance (can be switched on or off with polnoiseswitch), SI
SI_st=1/24;                                 % Noise sampling time, SI
SNH_ns=63122;                               % Noise seed, SNH
SNH_nv=factor3*(Snh_in);                    % Noise variance (can be switched on or off with polnoiseswitch), SNH
SNH_st=1/24;                                % Noise sampling time, SNH
SPO4_ns=73122;                              % Noise seed, SPO4
SPO4_nv=factor3*(Spo4_in);                  % Noise variance (can be switched on or off with polnoiseswitch), SPO4
SPO4_st=1/24;                               % Noise sampling time, SPO4
XI_ns=33122;                                % Noise seed, XI
XI_nv=factor3*(Xi_in*2);                    % Noise variance (can be switched on or off with polnoiseswitch), XI
XI_st=1/24;                                 % Noise sampling time, XI
XS_ns=43122;                                % Noise seed, XS
XS_nv=factor3*(Xs_in*2);                    % Noise variance (can be switched on or off with polnoiseswitch), XS
XS_st=1/24;                                 % Noise sampling time, XS
XBH_ns=53122;                               % Noise seed, XBH
XBH_nv=factor3*(Xbh_in*2);                  % Noise variance (can be switched on or off with polnoiseswitch), XBH
XBH_st=1/24;                                % Noise sampling time, XBH

SA_max=100*Sa_in;                           % g COD/m3
SA_min=0.1;                                 % g COD/m3
SF_max=100*Sf_in;                           % g COD/m3
SF_min=0.1;                                 % g COD/m
SI_max=100*Si_in;                           % g COD/m3
SI_min=0.1;                                 % g COD/m3
SNH_max=100*Snh_in;                         % g N/m3
SNH_min=0.1;                                % g N/m3
SPO4_max=100*Spo4_in;                       % g P/m3
SPO4_min=0.1;                               % g P/m3
XI_max=200*Xi_in;                           % g COD/m3
XI_min=0.1;                                 % g COD/m3
XS_max=200*Xs_in;                           % g COD/m3
XS_min=0.1;                                 % g COD/m3
XBH_max=200*Xbh_in;                         % g COD/m3
XBH_min=0.1;                                % g COD/m3

%8.2 Switch functions

polnoiseswitch = 1;                         % Switch noise term in the 'ASM' model block on (1) or off (0)


%% 9. first flush effect

FFfraction = 0.25;                          % Fraction of the TSS that is able to settle in the sewers

% ASM2d X state values
ASM2d_XINIT = [0.25 0.1 0.1 0.1 0.0 0.0 0.0 0.0 0.0 0.0 ]; % Initital conditions (10 states) XINIT= [TSS  XI  XS  XBH  XPAO XPP XPHA XBA  XMEOH  XMEP]

% Parameters
M_Max = 1000;                               % kg SS
Q_lim = 70000;                              % m3/d
n     = 15;                                 % Dimensionless
Ff    = 500;                                % Dimensionless, gain
SSPARS=[M_Max Q_lim n Ff];

%% 10. Sewer model

subarea = 4;

% 8.1 Model parameters (ASM1)

% Initialisation of the individual sewer model blocks
ASM2d_SEWERINIT=[zeros(1,23) 0.001];


% Parameters for individual sewer model block S-functions
A=1100;                                     % Area (m2)
C=150000;                                   % Tuning constant
Hmin=0.00;                                  % Minimum water level in tank
SPAR=[A C Hmin];

%% 11 Parameters temperature model block
TAmp = 5;                                   % Sine wave amplitude (deg. C)
TBias = 15;                                 % Sine wave bias (m3/d) (= average infiltration flow rate)
TFreq = 2*pi/364;                           % Sine wave frequency (rad/d)
TPhase = pi*8.5/24;                         % Sine wave phase shift

TdAmp = 0.5;                                % Sine wave amplitude (deg. C)
TdBias = 0;                                 % Sine wave bias (m3/d) (= average infiltration flow rate)
TdFreq = 2*pi;                              % Sine wave frequency (rad/d)
TdPhase = pi*0.8;                           % Sine wave phase shift





